# Generated by Django 4.0.2 on 2022-07-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_project_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('type', models.CharField(max_length=200, unique=True)),
                ('meaning', models.TextField()),
            ],
        ),
    ]
