# Generated by Django 4.0.2 on 2022-07-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_mydictionary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydictionary',
            name='type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mydictionary',
            name='words',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
